POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "Learn Go",
    "description": "reading the books about the Go programming language Golang"
}

POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "Learn Rust",
    "description": "reading the books about the Rust programming language Rust"
}

POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "Learn Javascript",
    "description": "reading the books about the Javascript programming"
}

GET http://localhost:3000/tasks HTTP/1.1


GET http://localhost:3000/tasks?status=DONE HTTP/1.1

GET http://localhost:3000/tasks?search=RUST HTTP/1.1


GET http://localhost:3000/tasks/77fa8987-e3e6-4039-be2e-c7cd8fbfa980 HTTP/1.1



DELETE http://localhost:3000/tasks/5c34d0a5-c1f1-4576-bb6c-32f505e174b3 HTTP/1.1


PATCH http://localhost:3000/tasks/77fa8987-e3e6-4039-be2e-c7cd8fbfa980/status HTTP/1.1
content-type: application/json

{
    "status": "DONE"
  }



///User


POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "Viserion",
    "password": "Aa1234567"
}


POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "Drogon",
    "password": "Aa1234567"
}

POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "Drogon",
    "password": "Aa1234567"
}

